export const TOWNS: Record<string, string> = {
  AMK: 'Ang Mo Kio',
  BB: 'Bukit Batok',
  BD: 'Bedok',
  BH: 'Bishan',
  BM: 'Bukit Merah',
  BP: 'Bukit Panjang',
  BT: 'Bukit Timah',
  CCK: 'Choa Chu Kang',
  CL: 'Clementi',
  CT: 'Central Area',
  GL: 'Geylang',
  HG: 'Hougang',
  JE: 'Jurong East',
  JW: 'Jurong West',
  KWN: 'Kallang/Whampoa',
  MP: 'Marine Parade',
  PG: 'Punggol',
  PRC: 'Pasir Ris',
  QT: 'Queenstown',
  SB: 'Sembawang',
  SGN: 'Serangoon',
  SK: 'Sengkang',
  TAP: 'Tampines',
  TG: 'Tengah',
  TP: 'Toa Payoh',
  WL: 'Woodlands',
  YS: 'Yishun',
};
